name: Build and push image
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version to be built"
        required: true
        type: string
permissions:
  contents: read

jobs:
  push_to_registries:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - name: Check out the repo
      uses: actions/checkout@v2
        
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ghcr.io/coveooss/acm_checker:${{ github.event.inputs.version }}
        labels: ${{ github.event.inputs.version }}